//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.LigneCommandes = new HashSet<LigneCommande>();
        }
    
        public int Commandeid { get; set; }
        public System.DateTime dateCom { get; set; }
        public Nullable<double> montantCom { get; set; }
        public int Clientid { get; set; }
        public int Userid { get; set; }
        public int EtatSoldeid { get; set; }
        public int EtatCommandeid { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneCommande> LigneCommandes { get; set; }
        public virtual Facture Facture { get; set; }
        public virtual Paiement Paiement { get; set; }
        public virtual Colis Coli { get; set; }
        public virtual EtatSolde EtatSolde { get; set; }
        public virtual EtatCommande EtatCommande { get; set; }
        public virtual Livraison Livraison { get; set; }
    }
}
