//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LigneCommande
    {
        public int LigneCommandeid { get; set; }
        public Nullable<int> qteCommande { get; set; }
        public Nullable<double> sommeLG { get; set; }
        public int Produitid { get; set; }
        public int Commandeid { get; set; }
    
        public virtual Produit Produit { get; set; }
        public virtual Commande Commande { get; set; }
    }
}
