//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CommandeContainer : DbContext
    {
        public CommandeContainer()
            : base("name=CommandeContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Commande> CommandeSet { get; set; }
        public virtual DbSet<Client> ClientSet { get; set; }
        public virtual DbSet<Livreur> LivreurSet { get; set; }
        public virtual DbSet<Versement> VersementSet { get; set; }
        public virtual DbSet<Livraison> LivraisonSet { get; set; }
        public virtual DbSet<EtatCommande> EtatCommandeSet { get; set; }
        public virtual DbSet<EtatSolde> EtatSoldeSet { get; set; }
        public virtual DbSet<Paiement> PaiementSet { get; set; }
        public virtual DbSet<Type> TypeSet { get; set; }
        public virtual DbSet<LigneCommande> LigneCommandeSet { get; set; }
        public virtual DbSet<Produit> ProduitSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Role> RoleSet { get; set; }
        public virtual DbSet<Colis> Colis { get; set; }
        public virtual DbSet<Facture> Factures { get; set; }
    }
}
